### ISSUE TITLE
!jira tips for new members

### ISSUE THREAD

**Issue by SlicedBlock** [mojira/mojira-discord-bot#113]
!jira tips would list tips for making a bug report or commenting/making requests, such as searching before making a report, explanation of duplicates, clones, avoid making requests when a mod is taking care of new reports etc, as it could be useful for new members.

**Comment by dericksonmark** [comment]
Hi!

If this is implemented, it should probably send a private message to the user (or give a link to a webpage where this information can be found) instead of just sending a message in the channel, as it's a _lot_ of information.

The way you've described it sounds like it should be organized into three different categories:
- Creating a report
- Resolutions and links (like clones, relations, duplications, blocks, discovered while testing)
- Requests
The one that may not be necessary is the requests one. There is already a pinned comment in all of the test channels that gives information on requests. To not make requests if new issues are already being looked at could be added to the pinned comment, and maybe whatever MojiraBot sends should include a link to these pinned comments. And now that I think about it a bit more, searching before creating a report may also not be necessary, as everyone on the Mojira Discord likely already knows about that.
Not that I think about it even more, there are some people on the Discord who join because they're not sure why their report was a duplicate. Maybe each section of the tips command could be configured (in the config file) as to whether or not it should send.

Lastly, if someone is asking about some information that can be found in the message that would be sent, there can be an optional argument to the command, which, if left empty, sends the message to the user who issued the command. However, if filled with a Discord username, it could send the message to a specific user. This part should only be accessible by helpers, moderators, and Mojang, as it could create a risk of 'spammage' otherwise.
