### ISSUE TITLE
Change request channel action from pinning to posting in separate channel

### ISSUE THREAD

**Issue by violine1101** [mojira/mojira-discord-bot#16]
Currently, all requests in request channels are pinned to that channel (see #8). However, as there is a limit of 50 pinned messages on Discord (which is also why we're currently not using this feature), it might be a good idea to change it or at least provide an option for the requests to also be mirrored in a different channel, maybe if a request is not acted upon after some time passed.

**Comment by SPGoding** [comment]
# Propose

Our workflow will become:
- An user sends request in one of the request channels;
- The bot reacts to the request with the waiting emoji immediately. This emoji can be used to separate multiple messages and reduce confusions like [this](https://discordapp.com/channels/647810384031645728/648555710157815818/679146218814963733) ;
- The bot forwards the request to a volunteer-only channel, and pre-reacts the copy with resolve emoji. Volunteers can simply select one emoji to react, instead of finding it manually. Since you volunteers are pretty smart, there won't be any [confusions](https://discordapp.com/channels/647810384031645728/654473670198165584/665602313364439056);
- A volunteer react to the bot's copy;
- After a configurable delay (in case of mis-reacting), the bot removes the copy and react the same emoji back to the original request.

Pros:
- For users:
    - Nothing has changed bigly.
- For volunteers
    - Much easier to track unresolved requests.

Cons:
- ???

**Comment by NeunEinser** [comment]
A tiny addition:
The possible reactions should be configurable in the config (and later probably per guild).
That way we can easily add reactions if they become necessary without changing code.

Other than that this sounds pretty much optimal

**Comment by NeunEinser** [comment]
Actually another thing I just thought about:
In some cases, it might be desirable to have a log of who did what. If the message in the volunteers channel gets deleted and the bot forwards the reaction, that information would be gone.

So it might be good to have maybe another log channel where the bot logs who reacted with which reaction to which request (probably one channel for all projects would be enough though).

Probably not too important though, and in case it's tricky to implement, it's not a big deal.

**Comment by Tora-B** [comment]
Why not just have the bot include a link to the original request message, so we can jump to it and respond to the original message? It's not quite as smooth of a workflow, but less disruptive of a change. It's probably cleanest to handle the majority of requests in the actual request channels anyway, and just use a separate channel to find requests that have slipped through the cracks.

**Comment by violine1101** [comment]
This is what an internal request message currently looks like in @SPGoding's PR:

![grafik](https://user-images.githubusercontent.com/12451842/75113872-d9860480-5651-11ea-8234-3d52fcc3e0b2.png)

I think it would be optimal if the bot would directly link to the original message in the embed (which should be possible). Embeds can have rich links, so it should not be as much of an issue. (Alternatively, embeds themselves can also point to an URL, similar to how I've done it with `SingleMention`; this might be another option to explore too)
Similarily, in the embed it would be nice if links to tickets and ticket IDs would be automatically replaced with a rich link to the ticket.
In request log messages, this is already implemented; this is what a log message currently looks like:

![grafik](https://user-images.githubusercontent.com/12451842/75113922-44cfd680-5652-11ea-85ce-c76d04af3f21.png)

IMO it might be a good idea to change this to something like `<User> resolved [this request](link to request) in #channel as <emoji>`

To pick up what @Tora-B said, perhaps it would be a good idea to have another delay for posting the requests to the internal channel in the first place, so that the workflow remains unchanged for requests that are rather recent. But then the advantage of having the reactions already prepared would be gone.

**Comment by SPGoding** [comment]
The `Channel` and `Message` fields in internal request embed are for the bot to read, so they are all plain texts. Maybe make the whole embed point to an URL is easier for me to implement.

> links to tickets and ticket IDs would be automatically replaced with a rich link to the ticket

Yes, I've thought about that ~~and forgot it~~. Might implement it in next commit.

> it might be a good idea to change this to something like <User> resolved [this request](link to request) in #channel as <emoji>

I was just not sure whether rich links can be used in embed description. Will change to this if there's no problem.

**Comment by Jack-McKalling** [comment]
Also would it help if the copy request not only provides pre-reactions, but also a description at the bottom of the embed? Such as:
![mojira bot request](https://user-images.githubusercontent.com/14236702/75274436-23fab300-5803-11ea-8b93-52c53c5e3af5.png)

Also a couple more could be added, that are used but less frequently?

**Comment by violine1101** [comment]
I think for that we could just have a pinned message for ourselves, we already know what each emoji means. Besides that, yes, the exact emojis can simply be configured in the bot config, so we can add new ones at any point without needing to reprogram the bot.

The blue checkmark would kinda lose its meaning though, since the bot would be the one who reacts to all the messages in the real request channels.

**Comment by SPGoding** [comment]
Blue one can still represents resolved-but-in-a-slightly-different-way solutions.

**Comment by Jack-McKalling** [comment]
Yes what SPG says. I forgot about that.
Regardless of where it would be placed, in the message or in the channel, I don't have an opinion. But I merely wanted to point out we need some description of each option, somewhere. New volunteers need to be explained how they are used, because people always ask for the obvious.

**Comment by Jack-McKalling** [comment]
Right now I can resolve a request using the hourglass reaction, which isn't in the pre-reactions. However that doesn't make any sense. The bot won't know what to do with that, and simply think it is finished. So either one of two things should happen:

The bot should ignore the hourglass reaction (or a different, configurable one)
The bot should ignore all reactions that aren't configured

Because allowing reactions that imply a request is still being looked into, is a state the bot should not be able to resolve to.

**Comment by SPGoding** [comment]
It's the volunteer's responsibility not to use strange reactions imo. And the pre-reactions are just suggestions, volunteers are free to use any other emoji they want to resolve a request if it's necessary.

**Comment by Jack-McKalling** [comment]
But I've seen a lot of inconsistency in mod's reactions. there's been a lot of cases they choose an undocumented one without explaining. That is also why I suggested the descriptions so we can provide all needed options (or help eachother find all of those)

**Comment by violine1101** [comment]
I've merged this change into master now – for any suggestions on how to improve it, please open new issues/PRs.
