### ISSUE TITLE
Add time of the request itself to internal request log

### ISSUE THREAD

**Issue by violine1101** [mojira/mojira-discord-bot#185]
## The Problem
The internal request log currently doesn't include date and time of the request itself, even though those could be useful.

## Possible Solution
Add another field for "Date/time" to the log messages.

**Comment by Jack-McKalling** [comment]
This might have come from the fact that internal requests don't (need to) include the time either because they basically happen at the same time as the original normally. But the log of a request as it got resolved, obviously doesn't.

A reason for adding this is so that when a request was resolved, we can compare the datetime from the log with the report itself to immediately see which change was the latter one.

**Comment by Jack-McKalling** [comment]
I don't think this PR is solving this issue. The issue is about the request log, not the internal request message
